[project]
name = "financial-analyst-skills"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.0",
    "pandas>=3.0.2",
    "python-multipart>=0.0.26",
    "torch>=2.11.0",
    "transformers>=5.5.4",
    "uvicorn>=0.44.0",
    "yfinance>=0.2.0",
]
